name: Build (Depots)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build & Release (Depots)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Get Versions
        id: versions
        run: |
          $ModVersion = Get-Content .\Directory.Build.props | Select-String -Pattern "<Version>([\d.]+)<\/Version>" | % { $($_.Matches.Groups[1]).Value }
          $ModVersion = $ModVersion -replace "\.0",""
          If ($ModVersion -notmatch "\.") { $ModVersion = "$ModVersion.0" }
          Write-Host "::set-output name=mod_version::$ModVersion"
          Write-Host "ModVersion: ""$ModVersion"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $GameVersion = Get-Content .\Directory.Build.props | Select-String -Pattern "<GameVersion>(e[\d.]+)<\/GameVersion>" | % { $($_.Matches.Groups[1]).Value }
          Write-Host "::set-output name=game_version::$GameVersion"
          Write-Host "GameVersion: ""$GameVersion"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $GameBranch = Get-Content .\Directory.Build.props | Select-String -Pattern "<GameBranch>(.+)<\/GameBranch>" | % { $($_.Matches.Groups[1]).Value }
          Write-Host "::set-output name=game_branch::$GameBranch"
          Write-Host "GameBranch: ""$GameBranch"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $RepoBranch = "${{github.ref}}"
          $RepoBranch = $RepoBranch.Split("/")[-1]
          If ($RepoBranch -eq "stable") { $RepoBranch = "" }
          If ($RepoBranch) { $RepoBranch = "-$RepoBranch" }
          Write-Host "::set-output name=repo_branch::$RepoBranch"
          Write-Host "RepoBranch: ""$RepoBranch"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $Prerelease = "${{github.ref}}"
          $Prerelease = $Prerelease.Split("/")[-1]
          If ($Prerelease -eq "stable") { $Prerelease = "false" } Else { $Prerelease = "true" }
          Write-Host "::set-output name=prerelease::$Prerelease"
          Write-Host "Prerelease: ""$Prerelease"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $ZipName = "BannerlordCheats_v$($ModVersion)_for_$($GameBranch)_$($GameVersion)"
          Write-Host "::set-output name=zip_name::$ZipName"
          Write-Host "ZipName: ""$ZipName"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $TagName = "v$ModVersion$RepoBranch"
          Write-Host "::set-output name=tag_name::$TagName"
          Write-Host "TagName: ""$TagName"""
          #---------------------------------------------------------------------------------------------------------------------------------------------------------------------
          $ReleaseTitle = "Release v$($ModVersion) for $($GameBranch) $($GameVersion)"
          Write-Host "::set-output name=release_title::$ReleaseTitle"
          Write-Host "ReleaseTitle: ""$ReleaseTitle"""

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 6.0.x
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Download DepotDownloader 2.4.7
        uses: i3h/download-release-asset@v1.3.2
        with:
          owner: SteamRE
          repo: DepotDownloader
          tag: DepotDownloader_2.4.7
          file: depotdownloader-2.4.7.zip

      - name: Extract DepotDownloader 2.4.7
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: depotdownloader-2.4.7.zip
          pathTarget: depotdownloader

      - name: Download Game Binaries
        run: >-
          dotnet depotdownloader/DepotDownloader.dll -app 261550 -depot 261551 -beta ${{steps.versions.outputs.game_version}} -username ${{secrets.STEAM_USERNAME}}
          -password ${{secrets.STEAM_PASSWORD}} -os windows -osarch 64 -filelist ./.github/resources/depotdownloader.txt -dir bannerlord;
        shell: pwsh

      - name: Build BannerlordCheats
        run: dotnet build BannerlordCheats.csproj  --configuration Release -p:GameFolder="$PWD\bannerlord" -p:UseNuGetAssemblies="False"
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Package Mod Files
        run: 7z a -tzip ../../${{steps.versions.outputs.zip_name}}.zip Cheats/
        working-directory: ./bannerlord/Modules

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.versions.outputs.zip_name}}
          path: ./${{steps.versions.outputs.zip_name}}.zip

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        if: ${{ github.ref_name == 'stable' || github.ref_name == 'beta' }}
        with:
          tag_name: ${{steps.versions.outputs.tag_name}}
          release_name: ${{steps.versions.outputs.release_title}}
          draft: false
          prerelease: ${{steps.versions.outputs.prerelease}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        id: upload_release_asset
        if: ${{ github.ref_name == 'stable' || github.ref_name == 'beta' }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./${{steps.versions.outputs.zip_name}}.zip
          asset_name: ${{steps.versions.outputs.zip_name}}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
